CREATE TABLE `drills` (
	`id` int AUTO_INCREMENT NOT NULL,
	`drillId` varchar(255) NOT NULL,
	`name` varchar(255) NOT NULL,
	`difficulty` varchar(50) NOT NULL DEFAULT 'Medium',
	`categories` json NOT NULL,
	`duration` varchar(50) NOT NULL DEFAULT '',
	`url` text,
	`isDirectLink` boolean NOT NULL DEFAULT false,
	`ageLevel` json,
	`tags` json,
	`problem` json,
	`goal` json,
	`drillType` varchar(100),
	`problems` json,
	`outcomes` json,
	`source` varchar(20) NOT NULL DEFAULT 'static',
	`isHidden` boolean NOT NULL DEFAULT false,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `drills_id` PRIMARY KEY(`id`),
	CONSTRAINT `drills_drillId_unique` UNIQUE(`drillId`)
);
